### ISSUE TITLE
Support for input types

### ISSUE THREAD

**Issue by fodier** [n1ru4l/graphql-schema-generator-rest#12]
Hi,

Here is a new test that currently fails:
```diff
diff --git a/src/__tests__/schema-generator.test.js b/src/__tests__/schema-generator.test.js
index 1f77b11..5d2ea0c 100644
--- a/src/__tests__/schema-generator.test.js
+++ b/src/__tests__/schema-generator.test.js
@@ -25,2 +25,6 @@ const typeDefs = gql`
 
+  input ColorInput {
+    name: String!
+  }
+
   type Mutation {
@@ -33,2 +37,7 @@ const typeDefs = gql`
       )
+    createColor(input: ColorInput!): Color
+      @rest(
+        route: "/colors"
+        method: "POST"
+      )
   }
@@ -201,2 +210,45 @@ describe(`General`, () => {
 
+  it(`supports a mutation with an input type`, async () => {
+    expect.assertions(2)
+
+    const fetcher = fetchMock
+      .sandbox()
+      .post('/colors', (url, opts) => {
+        const data = opts.body && JSON.parse(opts.body)
+        expect(data).toEqual({
+          name: 'yellow',
+        })
+
+        return JSON.stringify({
+          id: 'yellow',
+          name: 'yellow',
+        })
+      })
+
+    const schema = createRestSchema({ fetcher })
+    const mutation = `
+      mutation CreateColor($input: ColorInput!) {
+        createColor(input: $input) {
+          id
+          name
+        }
+      }
+    `
+    const variables = {
+      input: {
+        name: 'yellow',
+      },
+    }
+
+    const data = await graphql(schema, mutation, undefined, undefined, variables)
+    expect(data).toEqual({
+      data: {
+        createColor: {
+          id: 'yellow',
+          name: 'yellow',
+        },
+      },
+    })
+  })
+
   it(`supports a body mapper`, async () => {
```

What would be your preferred way of mapping input fields to the request body and URL? There’s no `body` parameter in the `createColor` query above. It could be:
```js
body: { name: "name" } // meaning body.name = input.name
```
or
```js
body: "CreateColorMapper" // from mappers.CreateColorMapper
```

It is probably out of scope for this feature request but I think that `body`, `query` and `provides` could all accept mapper names. Functions are more flexible to map things.

Thanks for your lib btw 🙇

**Comment by n1ru4l** [comment]
Hey there 😊!

Thank you for your interest and investigations.

I adjusted the test to match the current api by using the `body` param for mappings. (https://github.com/n1ru4l/graphql-schema-generator-rest/commit/2e0d86c4d0807385f9df45a8e41c1fae317bdf02#diff-cd802daf1f943b9fe03a7478a94ed829R39) and also fixed the issue 😁

Since `input` Types can exist also in other query/mutation params that have not the `input` name the first example you did mention does not make that much sense 😅

But I am totally fine with also supporting mappers for query, provides and body. I probably want them as a separate directive param.

Could you please open a new issue so we can tackle the feature isolated from this bug 😊

**Comment by fodier** [comment]
You’re fast, thx!
I’m going to open a new issue for the mappers.
