### ISSUE TITLE
Support mapper functions for body, query and provides parameters

### ISSUE THREAD

**Issue by fodier** [n1ru4l/graphql-schema-generator-rest#14]
Hi,

This query:
https://github.com/n1ru4l/graphql-schema-generator-rest/blob/afb0dce54689aacf894b98bc812b6812a6ba8a38/src/__tests__/schema-generator.test.js#L38-L39
leads to this request body:
```js
{
  input: {
    name: 'yellow'
  }
}
```

As far as I know, we can’t get the following request body by editing the `body` directive parameter:
```js
{
  name: 'yellow'
}
```

As discussed in #12, it would be great to support mapper functions for the `body`, `query` and `provides` directive parameters (in the spirit of `mapper`). Mapper functions would allow to map to anything, including the example above.

**Comment by n1ru4l** [comment]
I think it would be best to deprecate `mapper` on favor of `requestMapper`, `responseMapper` and `queryMapper`. 

We probably should not implement this for the provides param since I am going to replace it with the `@export` directive soon, or do you have some use cases where this would be beneficial?

Here is the current apollo-link spec that I want to stick to (if possible): https://github.com/apollographql/apollo-link-rest/blob/master/designs/initial.md

**Comment by fodier** [comment]
Yes I can do that 👍.
